name: wzk-env
dependencies:
- python=3.11
- pip

- setuptools>=68.2.2
- numpy>=1.26.0
- scipy>=1.11.0
- scikit-image>=0.19.3
- pandas>=1.5.2
- sympy>=1.11.1

- cython>=0.29.32
- pynput>=1.7.0
- einops>=0.6.0
- zlib>=1.2.12
- pyvista>=0.37.0
- matplotlib>=3.6.2
- fire>=0.4.0
- msgpack>=1.0.4
- requests>=2.31.1

- pip:
  - msgpack>=1.0.4
  - torch~=2.4
  - torchviz~=0.0.2
  - ray>=2.8
  - pyopt>=0.0.0
  - ortools>=9.5.2237
